name: Merge to Main / Deploy to Dev
on:
  push:
    branches:
      - main
jobs:
  print-positive:
    runs-on: ubuntu-latest
    env:
      MY_SECRET: ${{ secrets.MY_SECRET }}
    steps:
      - name: Echo Positive
        if: ${{ env.MY_SECRET }}
        run: |
          echo "YASSS QUEEN"
      - name: Echo Negative
        if: ${{ !env.MY_SECRET }}
        run: |
          echo "NO SIR"
